"""
Node [0] — Protocols (Interfaces)
=================================
Python typing.Protocol classes that define the public contracts between
every major component.  No implementation — pure shape.

Why this file exists (SOLID)
----------------------------
Dependency Inversion Principle: high-level components (Teacher, Assessor)
must depend on *abstractions*, not concrete classes.  Any object that
satisfies a protocol can be swapped in — including mocks in tests.

Interface Segregation Principle: each protocol is narrow.  Callers only
import the slice of the interface they actually use.

Protocols used by:
    IGraph        ← Teacher, Assessor
    IQueue        ← Teacher
    IHomework     ← Teacher
    ILessonSource ← Teacher (one entry in SOURCES satisfies this)
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


# ======================================================================== #
# IGraph — the knowledge graph surface                                      #
# Components: graph.py (SemanticGraph)                                      #
# ======================================================================== #

@runtime_checkable
class IGraph(Protocol):
    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    def update(self, concepts: list) -> list[str]: ...
    def save(self) -> None: ...
    def all_nodes(self) -> list[dict]: ...
    def all_edges(self) -> list[dict]: ...


# ======================================================================== #
# IQueue — lesson queue storage                                             #
# Components: queue_mgr.py (LessonQueue)                                   #
# ======================================================================== #

@runtime_checkable
class IQueue(Protocol):
    def add(self, lesson: dict) -> None: ...
    def remove(self, lesson_id: str) -> None: ...
    def list(self) -> list[dict]: ...
    def size(self) -> int: ...
    def known_urls(self) -> set[str]: ...
    def clear(self) -> None: ...


# ======================================================================== #
# IHomework — homework tracking                                             #
# Components: homework.py (HomeworkTracker)                                 #
# ======================================================================== #

@runtime_checkable
class IHomework(Protocol):
    def generate(self, stage: int, graph: IGraph) -> list[dict]: ...
    def tick(self, topic: str) -> None: ...
    def all(self) -> list[dict]: ...
    def pending(self) -> list[dict]: ...


# ======================================================================== #
# ILessonSource — one content provider                                      #
# Components: every entry in sources.SOURCES satisfies this                 #
# ======================================================================== #

class ILessonSource(Protocol):
    def search(self, query: str, max_results: int = 10) -> list[dict]: ...
    def fetch(self, item: dict) -> list[str]: ...


# ======================================================================== #
# IMetaState — temporary concept activation layer                          #
# Components: meta_state.py (MetaState)                                    #
# ======================================================================== #

@runtime_checkable
class IMetaState(Protocol):
    def reinforce(self, texts: list[str], gain: float | None = None) -> None: ...
    def decay_to(self, now: object | None = None) -> None: ...
    def active(self, threshold: float | None = None) -> dict: ...
    def top(self, n: int = 10) -> list: ...
    def snapshot(self) -> dict: ...


# ======================================================================== #
# IAttention — activation-weighted candidate reranking                     #
# Components: attention.py (AttentionBias)  — built in Step 04             #
# ======================================================================== #

@runtime_checkable
class IAttention(Protocol):
    def bias(self, candidates: list, scores: list[float],
             meta: IMetaState, strength: float) -> list: ...


# ======================================================================== #
# ITension — rolling-window ambiguity tension tracker                      #
# Components: tension.py (TensionTracker)  — built in Step 05              #
# ======================================================================== #

@runtime_checkable
class ITension(Protocol):
    def observe(self, concept: str, score: float) -> None: ...
    def hot(self, n: int = 5) -> list: ...
    def is_hot(self, concept: str) -> bool: ...


# ======================================================================== #
# INovelty — exposure tracking + novelty scoring                           #
# Components: novelty.py (NoveltyTracker)  — built in Phase B              #
# ======================================================================== #

@runtime_checkable
class INovelty(Protocol):
    def observe(self, concept: str) -> None: ...
    def novelty_score(self, concept: str) -> float: ...
    def snapshot(self) -> dict: ...


# ======================================================================== #
# IRegions — graph region index (stub until ~50k nodes)                   #
# Components: regions.py (RegionIndex)     — built in Step 06              #
# ======================================================================== #

@runtime_checkable
class IRegions(Protocol):
    def assign(self) -> None: ...
    def active_region(self) -> object: ...
    def nodes_in(self, region: object) -> list: ...


# ======================================================================== #
# IStability — entropy monitor + cognitive mode engine                     #
# Components: stability.py (StabilityMonitor)  — built in Phase D         #
# ======================================================================== #

@runtime_checkable
class IStability(Protocol):
    def tick(self, meta: IMetaState) -> float: ...
    def entropy(self) -> float: ...
    def current_mode(self, meta: IMetaState | None, regions: object | None) -> str: ...
    def mode_weights(self) -> dict: ...
    def snapshot(self) -> dict: ...


# ======================================================================== #
# V3 Interfaces                                                             #
# ======================================================================== #

@runtime_checkable
class IMemory(Protocol):
    """Temporal memory [Mem] — working / episodic / semantic layers."""
    def reinforce(self, concepts: list, gain_override: object | None) -> None: ...
    def value(self, concept: str) -> float: ...
    def decay_to(self, now: object | None) -> None: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IEpisodes(Protocol):
    """Episodic trace graph [Ep]."""
    def record(self, concepts: list, ambiguity: float,
               region: object | None, outcome: str) -> object: ...
    def transitions_from(self, concept: str) -> dict: ...
    def recent(self, n: int) -> list: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IPredictor(Protocol):
    """Predictive activation engine [P]."""
    def predict(self, context_concepts: list) -> list: ...
    def pre_activate(self, context_concepts: list, memory: IMemory) -> list: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IContradiction(Protocol):
    """Contradiction registry [X]."""
    def observe(self, concepts: list) -> list: ...
    def unresolved(self) -> list: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IGoals(Protocol):
    """Goal formation engine [Go]."""
    def current_goal(self) -> str: ...
    def drive_scores(self) -> dict: ...
    def tick(self) -> str: ...
    def snapshot(self) -> dict: ...


# ======================================================================== #
# V3-9..20 + V4 protocols                                                   #
# ======================================================================== #

@runtime_checkable
class IAgents(Protocol):
    def arbitrate(self, candidates: list, meta=None, memory=None,
                  tension_tracker=None, novelty_tracker=None) -> list: ...
    def dominant_agent(self) -> str: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IWorldModel(Protocol):
    def observe(self, source: str, target: str, relation: str,
                strength: float = 1.0) -> None: ...
    def predict_effects(self, concept: str) -> list: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IEvolver(Protocol):
    def tick(self) -> None: ...
    def current_params(self) -> dict: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IPredictionError(Protocol):
    def observe(self, predicted: list, actual: list) -> float: ...
    def mean_error(self) -> float: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IActiveInference(Protocol):
    def step(self) -> dict | None: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IBinding(Protocol):
    def update(self) -> int: ...
    def bridge_strength(self, concept: str) -> float: ...
    def top_bridges(self, n: int = 20) -> list: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IEnergy(Protocol):
    def spend(self, activity: str, units: int = 1) -> bool: ...
    def replenish(self) -> None: ...
    def level(self) -> float: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class ISelfModel(Protocol):
    def tick(self) -> None: ...
    def mean_accuracy(self) -> float: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IIdentity(Protocol):
    def observe(self) -> None: ...
    def traits(self) -> dict: ...
    def personality_summary(self) -> str: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IMetaLearner(Protocol):
    def tick(self) -> None: ...
    def best_strategy(self) -> str: ...
    def strategy_scores(self) -> dict: ...
    def snapshot(self) -> dict: ...


@runtime_checkable
class IEcology(Protocol):
    def tick(self, context_concepts: list | None = None) -> dict: ...
    def snapshot(self) -> dict: ...
